export const Fonts = {
  Mulish: {
    ExtraLight: "Mulish-ExtraLight",
    light: "Mulish-Light",
    Regular: "Mulish-Regular",
    Medium: "Mulish-Medium",
    SemiBold: "Mulish-SemiBold",
    Bold: "Mulish-Bold",
    ExtraBold: "Mulish-ExtraBold",
    Black: "Mulish-Black",
    Italic: {
      ExtraLight: "Mulish-ExtraLightItalic",
      light: "Mulish-LightItalic",
      Medium: "Mulish-MediumItalic",
      SemiBold: "Mulish-SemiBoldItalic",
      Bold: "Mulish-BoldItalic",
      ExtraBold: "Mulish-ExtraBoldItalic",
      Black: "Mulish-BlackItalic",
    },
  },
  Nunito: {
    ExtraLight: "Nunito-ExtraLight",
    light: "Nunito-Light",
    Regular: "Nunito-Regular",
    Medium: "Nunito-Medium",
    SemiBold: "Nunito-SemiBold",
    Bold: "Nunito-Bold",
    ExtraBold: "Nunito-ExtraBold",
    Black: "Nunito-Black",
    Italic: {
      ExtraLight: "Nunito-ExtraLightItalic",
      light: "Nunito-LightItalic",
      Medium: "Nunito-MediumItalic",
      SemiBold: "Nunito-SemiBoldItalic",
      Bold: "Nunito-BoldItalic",
      ExtraBold: "Nunito-ExtraBoldItalic",
      Black: "Nunito-BlackItalic",
    },
  },
  Roboto: {
    light: "Roboto-Light",
    Regular: "Roboto-Regular",
    Medium: "Roboto-Medium",
    Bold: "Roboto-Bold",
    Black: "Roboto-Black",
    Italic: {
      light: "Nunito-LightItalic",
      Medium: "Nunito-MediumItalic",
      Bold: "Nunito-BoldItalic",
      Black: "Nunito-BlackItalic",
    },
  },
};
