import { Allflag } from "./flag";
export const countries = [
  { name: "United Arab Emirates (the)", code: "AE", flag: Allflag.AE , dail_code: "+971"},
  { name: "Afghanistan", code: "AF", flag: Allflag.AF , dail_code: "+93"},
  { name: "Aland Islands", code: "AX", flag: Allflag.AX , dail_code: "+358"},
  { name: "Albania", code: "AL", flag: Allflag.AL , dail_code: "+355"},
  { name: "Algeria", code: "DZ", flag: Allflag.DZ, dail_code: "+213" },
  { name: "Andorra", code: "AD", flag: Allflag.AD , dail_code: "+376"},
  { name: "Angola", code: "AO", flag: Allflag.AO , dail_code: "+244"},
  { name: "Anguilla", code: "AI", flag: Allflag.AI , dail_code: "+1264"},
  { name: "Antigua and Barbuda", code: "AG", flag: Allflag.AG , dail_code: "+1268"},
  { name: "Argentina", code: "AR", flag: Allflag.AR , dail_code: "+54"},
  { name: "Armenia", code: "AM", flag: Allflag.AM , dail_code: "+374" },
  { name: "Aruba", code: "AW", flag: Allflag.AW ,  dail_code: "+297"},
  { name: "Australia", code: "AU", flag: Allflag.AU , dail_code: "+61"},
  { name: "Austria", code: "AT", flag: Allflag.AT , dail_code: "+43"},
  { name: "Azerbaijan", code: "AZ", flag: Allflag.AZ , dail_code: "+994"},
  { name: "Bahamas", code: "BS", flag: Allflag.BS , dail_code: "+1242"},
  { name: "Bahrain", code: "BH", flag: Allflag.BH , dail_code: "+973"},
  { name: "Bangladesh", code: "BD", flag: Allflag.BD , dail_code: "+880"},
  { name: "Barbados", code: "BB", flag: Allflag.BB , dail_code: "+1246"},
  { name: "Belarus", code: "BY", flag: Allflag.BY , dail_code: "+375"},
  { name: "Belgium", code: "BE", flag: Allflag.BE , dail_code: "+32"},
  { name: "Belize", code: "BZ", flag: Allflag.BZ , dail_code: "+501"},
  { name: "Benin", code: "BJ", flag: Allflag.BJ , dail_code: "+229"},
  { name: "Bermuda", code: "BM", flag: Allflag.BM , dail_code: "+1441"},
  { name: "Bhutan", code: "BT", flag: Allflag.BT , dail_code: "+975"},
  { name: "Bolivia", code: "BO", flag: Allflag.BO , dail_code: "+591"},
  { name: "Bosnia and Herzegovina", code: "BA", flag: Allflag.BA , dail_code: "+387"},
  { name: "Botswana", code: "BW", flag: Allflag.BW , dail_code: "+267"},
  { name: "Brazil", code: "BR", flag: Allflag.BR , dail_code: "+55"},
  { name: "Brunei Darussalam", code: "BN", flag: Allflag.BN , dail_code: "+673"},
  { name: "Bulgaria", code: "BG", flag: Allflag.BG , dail_code: "+359"},
  { name: "Burkina Faso", code: "BF", flag: Allflag.BF , dail_code: "+226"},
  { name: "Burundi", code: "BI", flag: Allflag.BI , dail_code: "+257"},
  { name: "Cambodia", code: "KH", flag: Allflag.KH , dail_code: "+855"},
  { name: "Cameroon", code: "CM", flag: Allflag.CM , dail_code: "+237"},
  { name: "Canada", code: "CA", flag: Allflag.CA , dail_code: "+1"},
  { name: "Cape Verde", code: "CV", flag: Allflag.CV , dail_code: "+238"},
  { name: "Cayman Islands", code: "KY", flag: Allflag.KY , dail_code: "+1345"},
  { name: "Central African Republic", code: "CF", flag: Allflag.CF , dail_code: "+236"},
  { name: "Chad", code: "TD", flag: Allflag.TD, dail_code: "+235" },
  { name: "Chile", code: "CL", flag: Allflag.CL , dail_code: "+56"},
  { name: "China", code: "CN", flag: Allflag.CN , dail_code: "+86"},
  { name: "Colombia", code: "CO", flag: Allflag.CO , dail_code: "+57"},
  { name: "Comoros", code: "KM", flag: Allflag.KM , dail_code: "+269"},
  { name: "Congo", code: "CG", flag: Allflag.CG , dail_code: "+242"},
  {
    name: "Congo, Democratic Republic of the Congo",
    code: "CD",
    flag: Allflag.CD,
    dail_code: "+243",
  },
  { name: "Costa Rica", code: "CR", flag: Allflag.CR , dail_code: "+506"},
  { name: "Cote D'Ivoire", code: "CI", flag: Allflag.CI, dail_code: "+225" },
  { name: "Croatia", code: "HR", flag: Allflag.HR , dail_code: "+385"},
  { name: "Cuba", code: "CU", flag: Allflag.CU , dail_code: "+53"},
  { name: "Cyprus", code: "CY", flag: Allflag.CY , dail_code: "+357"},
  { name: "Czech Republic", code: "CZ", flag: Allflag.CZ , dail_code: "+420"},
  { name: "Denmark", code: "DK", flag: Allflag.DK , dail_code: "+45"},
  { name: "Djibouti", code: "DJ", flag: Allflag.DJ,   dail_code: "+253" },
  { name: "Dominica", code: "DM", flag: Allflag.DM , dail_code: "+1767"},
  { name: "Dominican Republic", code: "DO", flag: Allflag.DO , dail_code: "+1849"},
  { name: "Ecuador", code: "EC", flag: Allflag.EC , dail_code: "+593"},
  { name: "Egypt", code: "EG", flag: Allflag.EG , dail_code: "+20"},
  { name: "El Salvador", code: "SV", flag: Allflag.SV , dail_code: "+503"},
  { name: "Equatorial Guinea", code: "GQ", flag: Allflag.GQ , dail_code: "+240"},
  { name: "Eritrea", code: "ER", flag: Allflag.ER , dail_code: "+291"},
  { name: "Estonia", code: "EE", flag: Allflag.EE , dail_code: "+372"},
  { name: "Ethiopia", code: "ET", flag: Allflag.ET , dail_code: "+251"},
  { name: "Falkland Islands (Malvinas)", code: "FK", flag: Allflag.FK , dail_code: "+500"},
  { name: "Fiji", code: "FJ", flag: Allflag.FJ , dail_code: "+679"},
  { name: "Finland", code: "FI", flag: Allflag.FI , dail_code: "+358"},
  { name: "France", code: "FR", flag: Allflag.FR , dail_code: "+33"},
  { name: "French Polynesia", code: "PF", flag: Allflag.PF , dail_code: "+689"},
  { name: "Gabon", code: "GA", flag: Allflag.GA , dail_code: "+241"},
  { name: "Gambia", code: "GM", flag: Allflag.GM , dail_code: "+220"},
  { name: "Georgia", code: "GE", flag: Allflag.GE , dail_code: "+995"},
  { name: "Germany", code: "DE", flag: Allflag.DE , dail_code: "+49"},
  { name: "Ghana", code: "GH", flag: Allflag.GH , dail_code: "+233"},
  { name: "Gibraltar", code: "GI", flag: Allflag.GI , dail_code: "+350"},
  { name: "Greece", code: "GR", flag: Allflag.GR , dail_code: "+30"},

  { name: "Grenada", code: "GD", flag: Allflag.GD , dail_code: "+1473"},

  { name: "Guatemala", code: "GT", flag: Allflag.GT , dail_code: "+502"},
  { name: "Guernsey", code: "GG", flag: Allflag.GG , dail_code: "+44"},
  { name: "Guinea", code: "GN", flag: Allflag.GN , dail_code: "+224"},
  { name: "Guinea-Bissau", code: "GW", flag: Allflag.GW , dail_code: "+245"},
  { name: "Guyana", code: "GY", flag: Allflag.GY , dail_code: "+592"},
  { name: "Haiti", code: "HT", flag: Allflag.HT , dail_code: "+509"},
  { name: "Honduras", code: "HN", flag: Allflag.HN , dail_code: "+504"},
  { name: "Hong Kong", code: "HK", flag: Allflag.HK , dail_code: "+852"},
  { name: "Hungary", code: "HU", flag: Allflag.HU , dail_code: "+36"},
  { name: "Iceland", code: "IS", flag: Allflag.IS , dail_code: "+354"},
  { name: "India", code: "IN", flag: Allflag.IN , dail_code: "+91"},
  { name: "Indonesia", code: "ID", flag: Allflag.ID , dail_code: "+62"},
  { name: "Iran, Islamic Republic of", code: "IR", flag: Allflag.IR , dail_code: "+98"},
  { name: "Iraq", code: "IQ", flag: Allflag.IQ , dail_code: "+964"},
  { name: "Ireland", code: "IE", flag: Allflag.IE , dail_code: "+353"},
  { name: "Isle of Man", code: "IM", flag: Allflag.IM , dail_code: "+44"},
  { name: "Israel", code: "IL", flag: Allflag.IL , dail_code: "+972"},

  { name: "Jamaica", code: "JM", flag: Allflag.JM , dail_code: "+1876"},
  { name: "Japan", code: "JP", flag: Allflag.JP , dail_code: "+81"},
  { name: "Jersey", code: "JE", flag: Allflag.JE , dail_code: "+44"},
  { name: "Jordan", code: "JO", flag: Allflag.JO , dail_code: "+962"},
  { name: "Kazakhstan", code: "KZ", flag: Allflag.KZ , dail_code: "+7"},
  { name: "Kenya", code: "KE", flag: Allflag.KE , dail_code: "+254"},

  {
    name: "Korea, Democratic People's Republic of",
    code: "KP",
    flag: Allflag.KP,
    dail_code: "+850",
  },
  { name: "Korea, Republic of", code: "KR", flag: Allflag.KR , dail_code: "+82"},

  { name: "Kuwait", code: "KW", flag: Allflag.KW , dail_code: "+965"},
  { name: "Kyrgyzstan", code: "KG", flag: Allflag.KG , dail_code: "+996"},
  { name: "Lao People's Democratic Republic", code: "LA", flag: Allflag.LA , dail_code: "+856"},
  { name: "Latvia", code: "LV", flag: Allflag.LV , dail_code: "+371"},
  { name: "Lebanon", code: "LB", flag: Allflag.LB , dail_code: "+961"},
  { name: "Lesotho", code: "LS", flag: Allflag.LS , dail_code: "+266"},
  { name: "Liberia", code: "LR", flag: Allflag.LR , dail_code: "+231"},
  { name: "Libyan Arab Jamahiriya", code: "LY", flag: Allflag.LY , dail_code: "+218"},
  { name: "Liechtenstein", code: "LI", flag: Allflag.LI , dail_code: "+423"},
  { name: "Lithuania", code: "LT", flag: Allflag.LT , dail_code: "+370"},
  { name: "Luxembourg", code: "LU", flag: Allflag.LU , dail_code: "+352"},
  { name: "Macao", code: "MO", flag: Allflag.MO , dail_code: "+853"},
  {
    name: "Macedonia",
    code: "MK",
    flag: Allflag.MK,
    dail_code: "+389",

  },
  { name: "Madagascar", code: "MG", flag: Allflag.MG , dail_code: "+261"},
  { name: "Malawi", code: "MW", flag: Allflag.MW , dail_code: "+265"},
  { name: "Malaysia", code: "MY", flag: Allflag.MY , dail_code: "+60"},
  { name: "Maldives", code: "MV", flag: Allflag.MV , dail_code: "+960"},
  { name: "Mali", code: "ML", flag: Allflag.ML , dail_code: "+223"},
  { name: "Malta", code: "MT", flag: Allflag.MT , dail_code: "+356"},
  { name: "Mauritius", code: "MU", flag: Allflag.MU , dail_code: "+230"},

  { name: "Mexico", code: "MX", flag: Allflag.MX , dail_code: "+52"},
  { name: "Micronesia, Federated States of", code: "FM", flag: Allflag.FM , dail_code: "+691"},
  { name: "Moldova, Republic of", code: "MD", flag: Allflag.MD , dail_code: "+373"},
  { name: "Monaco", code: "MC", flag: Allflag.MC , dail_code: "+377"},
  { name: "Mongolia", code: "MN", flag: Allflag.MN , dail_code: "+976"},
  { name: "Montenegro", code: "ME", flag: Allflag.ME , dail_code: "+382"},
  { name: "Montserrat", code: "MS", flag: Allflag.MS , dail_code: "+1664"},
  { name: "Morocco", code: "MA", flag: Allflag.MA , dail_code: "+212"},
  { name: "Mozambique", code: "MZ", flag: Allflag.MZ , dail_code: "+258"},
  { name: "Myanmar", code: "MM", flag: Allflag.MM , dail_code: "+95"},
  { name: "Namibia", code: "NA", flag: Allflag.NA , dail_code: "+264"},

  { name: "Nepal", code: "NP", flag: Allflag.NP , dail_code: "+977"},
  { name: "Netherlands", code: "NL", flag: Allflag.NL , dail_code: "+31"},
  { name: "Netherlands Antilles", code: "AN", flag: Allflag.AN , dail_code: "+599"},

  { name: "New Zealand", code: "NZ", flag: Allflag.NZ , dail_code: "+64"},
  { name: "Nicaragua", code: "NI", flag: Allflag.NI , dail_code: "+505"},
  { name: "Niger", code: "NE", flag: Allflag.NE , dail_code: "+227"},
  { name: "Nigeria", code: "NG", flag: Allflag.NG , dail_code: "+234"},
  { name: "Niue", code: "NU", flag: Allflag.NU , dail_code: "+683"},
  { name: "Norway", code: "NO", flag: Allflag.NO , dail_code: "+47"},
  { name: "Oman", code: "OM", flag: Allflag.OM  , dail_code: "+968"},
  { name: "Pakistan", code: "PK", flag: Allflag.PK , dail_code: "+92"},
  { name: "Palau", code: "PW", flag: Allflag.PW , dail_code: "+680"},
  { name: "Panama", code: "PA", flag: Allflag.PA , dail_code: "+507"},
  { name: "Papua New Guinea", code: "PG", flag: Allflag.PG , dail_code: "+675"},
  { name: "Paraguay", code: "PY", flag: Allflag.PY , dail_code: "+595"},
  { name: "Peru", code: "PE", flag: Allflag.PE , dail_code: "+51"},
  { name: "Philippines", code: "PH", flag: Allflag.PH , dail_code: "+63"},

  { name: "Poland", code: "PL", flag: Allflag.PL , dail_code: "+48"},
  { name: "Portugal", code: "PT", flag: Allflag.PT , dail_code: "+351"},
  { name: "Puerto Rico", code: "PR", flag: Allflag.PR , dail_code: "+1939"},
  { name: "Qatar", code: "QA", flag: Allflag.QA , dail_code: "+974"},

  { name: "Romania", code: "RO", flag: Allflag.RO , dail_code: "+40"},
  { name: "Russian Federation", code: "RU", flag: Allflag.RU , dail_code: "+7"},
  { name: "Rwanda", code: "RW", flag: Allflag.RW , dail_code: "+250"},

  { name: "Saint Helena", code: "SH", flag: Allflag.SH , dail_code: "+290"},
  { name: "Saint Kitts and Nevis", code: "KN", flag: Allflag.KN , dail_code: "+1869"  },
  { name: "Saint Lucia", code: "LC", flag: Allflag.LC , dail_code: "+1758"},

  { name: "Saint Vincent and the Grenadines", code: "VC", flag: Allflag.VC , dail_code: "+1784"},
  { name: "Samoa", code: "WS", flag: Allflag.WS , dail_code: "+685"},
  { name: "San Marino", code: "SM" , flag: Allflag.SM , dail_code: "+378"},
  { name: "Sao Tome and Principe", code: "ST", flag: Allflag.ST , dail_code: "+239"},
  { name: "Saudi Arabia", code: "SA", flag: Allflag.SA , dail_code: "+966"},
  { name: "Senegal", code: "SN", flag: Allflag.SN , dail_code: "+221"},
  { name: "Serbia", code: "RS", flag: Allflag.RS , dail_code: "+381"},

  { name: "Seychelles", code: "SC", flag: Allflag.SC , dail_code: "+248"},
  { name: "Sierra Leone", code: "SL", flag: Allflag.SL , dail_code: "+232"},
  { name: "Singapore", code: "SG", flag: Allflag.SG , dail_code: "+65"},

  { name: "Slovakia", code: "SK", flag: Allflag.SK  , dail_code: "+421"},
  { name: "Slovenia", code: "SI", flag: Allflag.SI , dail_code: "+386"},
  { name: "Solomon Islands", code: "SB", flag: Allflag.SB , dail_code: "+677"},
  { name: "Somalia", code: "SO", flag: Allflag.SO , dail_code: "+252"},
  { name: "South Africa", code: "ZA", flag: Allflag.ZA , dail_code: "+27"},

  { name: "Spain", code: "ES", flag: Allflag.ES , dail_code: "+34"},
  { name: "Sri Lanka", code: "LK", flag: Allflag.LK , dail_code: "+94"},
  { name: "Sudan", code: "SD", flag: Allflag.SD , dail_code: "+249"},
  { name: "Suriname", code: "SR", flag: Allflag.SR , dail_code: "+597"},

  { name: "Swaziland", code: "SZ", flag: Allflag.SZ , dail_code: "+268"},
  { name: "Sweden", code: "SE", flag: Allflag.SE , dail_code: "+46"},
  { name: "Switzerland", code: "CH", flag: Allflag.CH , dail_code: "+41"},
  { name: "Syrian Arab Republic", code: "SY", flag: Allflag.SY , dail_code: "+963"},
  { name: "Taiwan, Province of China", code: "TW", flag: Allflag.TW , dail_code: "+886"},
  { name: "Tajikistan", code: "TJ", flag: Allflag.TJ , dail_code: "+992"},
  { name: "Tanzania, United Republic of", code: "TZ", flag: Allflag.TZ , dail_code: "+255"},
  { name: "Thailand", code: "TH", flag: Allflag.TH , dail_code: "+66"},
  { name: "Timor-Leste", code: "TL", flag: Allflag.TL , dail_code: "+670"},
  { name: "Togo", code: "TG", flag: Allflag.TG , dail_code: "+228"},

  { name: "Tonga", code: "TO", flag: Allflag.TO , dail_code: "+676"},
  { name: "Trinidad and Tobago", code: "TT", flag: Allflag.TT , dail_code: "+1868"},
  { name: "Tunisia", code: "TN", flag: Allflag.TN , dail_code: "+216"},
  { name: "Turkey", code: "TR", flag: Allflag.TR , dail_code: "+90"},
  { name: "Turkmenistan", code: "TM", flag: Allflag.TM , dail_code: "+993"},
  { name: "Turks and Caicos Islands", code: "TC", flag: Allflag.TC , dail_code: "+1649"},
  { name: "Tuvalu", code: "TV", flag: Allflag.TV , dail_code: "+688"},
  { name: "Uganda", code: "UG", flag: Allflag.UG , dail_code: "+256"},
  { name: "Ukraine", code: "UA", flag: Allflag.UA , dail_code: "+380"},

  { name: "United Kingdom", code: "GB", flag: Allflag.GB , dail_code: "+44"},
  { name: "United States", code: "US", flag: Allflag.US , dail_code: "+1"},
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    flag: Allflag.UM,
    dail_code: "+1",
  },
  { name: "Uruguay", code: "UY", flag: Allflag.UY , dail_code: "+598" },
  { name: "Uzbekistan", code: "UZ", flag: Allflag.UZ , dail_code: "+998"},
  { name: "Vanuatu", code: "VU", flag: Allflag.VU , dail_code: "+678"},
  { name: "Venezuela", code: "VE", flag: Allflag.VE , dail_code: "+58"},
  { name: "Viet Nam", code: "VN", flag: Allflag.VN , dail_code: "+84"},
  { name: "Virgin Islands, British", code: "VG", flag: Allflag.VG , dail_code: "+1284" },
  { name: "Virgin Islands, U.s.", code: "VI", flag: Allflag.VI , dail_code: "+1340"},
  { name: "Wallis and Futuna", code: "WF", flag: Allflag.WF , dail_code: "+681"},
  { name: "Western Sahara", code: "EH", flag: Allflag.EH , dail_code: "+212"},
  { name: "Yemen", code: "YE", flag: Allflag.YE , dail_code: "+967"},
  { name: "Zambia", code: "ZM", flag: Allflag.ZM  , dail_code: "+260"},
  { name: "Zimbabwe", code: "ZW", flag: Allflag.ZW , dail_code: "+263" },
];

// countryPhoneCodes
